'use strict';
let Koa = require('koa');
let path = require('path');
let wechat = require('./wechat/g');
let util = require('./libs/util');
let config = require('./config');
let weixin = require('./weixin');
let wechat_file = path.join(__dirname,'./config/wechat.txt');
let app = new Koa();
app.use(wechat(config.wechat,weixin.reply));
app.listen(3100);
console.log('start 3100');